// app/cra-react18/src/views/Category/index.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { NavLink, useParams, useSearchParams } from "react-router-dom";
import styled from "styled-components";
import { Breadcrumb, Divider, Empty, Pagination, Skeleton } from "antd";
import BaseLayout from "@/components/BaseLayout";
import { ArticleDTO } from "@/bean/dto";
import { articleService } from "@/services/article";
import { setScrollTop } from "@/utils/dom";
import { useAsyncLoading } from "@/hooks/async";
import CardArticle from "@/components/CardArticle";

const ArticleList = styled.section``;

const Category: React.FC = () => {
    const { name } = useParams();

    const [articleList, setArticleList] = useState<ArticleDTO[]>([]);

    const [total, setTotal] = useState(0);

    const [searchParams, setSearchParams] = useSearchParams();

    const qsPageNo = searchParams.get("pageNo");
    const pageNo = qsPageNo ? Number(qsPageNo) : 1;
    const [pageInfo, setPageInfo] = useState({ pageNo, pageSize: 6 });

    const prevPageNo = useRef(pageInfo.pageNo);

    const handleGetArticleList = useCallback(
        async (isChangePage: boolean) => {
            const { data, total } = await articleService.pageByCategory({
                ...pageInfo,
                keyword: name as string,
            });
            setArticleList(data);
            setTotal(total);
            if (isChangePage) {
                setScrollTop({
                    useAnimation: true,
                    duration: 0.3,
                });
            }
        },
        [pageInfo, name],
    );

    const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList, [pageInfo, name]);

    useEffect(() => {
        const qsPageNo = searchParams.get("pageNo");
        const pageNo = qsPageNo ? Number(qsPageNo) : 1;
        if (pageNo && pageNo > 0 && pageNo !== prevPageNo.current) {
            setPageInfo((prevPageInfo) => ({
                ...prevPageInfo,
                pageNo,
            }));
        }
    }, [searchParams]);

    useEffect(() => {
        const isChangePage = pageInfo.pageNo !== prevPageNo.current;
        getPageList(isChangePage);
    }, [pageInfo, getPageList]);

    useEffect(() => {
        prevPageNo.current = pageInfo.pageNo;
    }, [pageInfo]);

    // 分页改变
    const onPageNoChange = (page: number) => {
        setSearchParams({ pageNo: String(page) });
    };

    return (
        <BaseLayout>
            <Skeleton loading={loading} active={true} paragraph={{ rows: 12 }}>
                {articleList.length > 0 ? (
                    <>
                        <Breadcrumb>
                            <Breadcrumb.Item>
                                <NavLink to="/">首页</NavLink>
                            </Breadcrumb.Item>
                            <Breadcrumb.Item>
                                <NavLink to="/categories">所有分类</NavLink>
                            </Breadcrumb.Item>
                            <Breadcrumb.Item>{name}</Breadcrumb.Item>
                        </Breadcrumb>

                        <Divider />

                        <ArticleList>
                            {articleList.map((article) => (
                                <CardArticle article={article} key={article.id} />
                            ))}
                        </ArticleList>

                        <Pagination
                            current={pageInfo.pageNo}
                            pageSize={pageInfo.pageSize}
                            total={total}
                            showLessItems={true}
                            simple={true}
                            showSizeChanger={false}
                            onChange={onPageNoChange}
                            className="mt-5 justify-center"
                        />
                    </>
                ) : (
                    <Empty />
                )}
            </Skeleton>
        </BaseLayout>
    );
};

export default Category;

// app/vite-vue3/src/views/category/index.vue
<!--
 * @author: Tusi
 * @description: 分类
-->
<template>
    <base-layout>
        <a-breadcrumb>
            <a-breadcrumb-item><router-link to="/">首页</router-link></a-breadcrumb-item>
            <a-breadcrumb-item><router-link to="/categories">所有分类</router-link></a-breadcrumb-item>
            <a-breadcrumb-item>{{ $route.params.name }}</a-breadcrumb-item>
        </a-breadcrumb>

        <a-divider />

        <a-skeleton :loading="loading" active :paragraph="{ rows: 12 }">
            <template v-if="articleList.length > 0">
                <section class="article-list">
                    <card-article v-for="article in articleList" :key="article.id" :article="article" />
                </section>

                <a-pagination
                    class="pagination-common"
                    v-model:current="pageInfo.pageNo"
                    v-model:pageSize="pageInfo.pageSize"
                    :total="total"
                    show-less-items
                    simple
                    @change="onPageNoChange"
                />
            </template>

            <template v-else>
                <a-empty />
            </template>
        </a-skeleton>
    </base-layout>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, watch } from "vue";
import { LocationQuery, useRoute, useRouter } from "vue-router";
import { ArticleDTO } from "@/bean/dto";
import { articleService } from "@/services/article";
import { useAsyncLoading } from "@/hooks/async";
import CardArticle from "@/components/card/card-article.vue";
import { setScrollTop } from "@/utils/dom";

export default defineComponent({
    name: "Home",
    components: {
        CardArticle,
    },
    setup() {
        // route
        const route = useRoute();
        const router = useRouter();

        const articleList = ref<ArticleDTO[]>([]);

        const pageInfo = reactive({
            pageNo: 1,
            pageSize: 6,
        });

        const total = ref(0);

        const handleGetArticleList = async (isChangePage: boolean) => {
            const res = await articleService.pageByCategory({
                ...pageInfo,
                keyword: route.params.name as string,
            });
            articleList.value = res.data;
            total.value = res.total;
            setScrollTop({
                useAnimation: isChangePage,
                duration: 0.3,
            });
        };

        const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList);

        // 监听路由变化调用查询
        watch(
            () => route.query,
            (val: LocationQuery, oldVal) => {
                const { pageNo } = val;
                if (pageNo) {
                    pageInfo.pageNo = Number(pageNo);
                } else {
                    pageInfo.pageNo = 1;
                }
                const isChangePage = pageNo !== oldVal?.pageNo;
                getPageList(isChangePage);
            },
            {
                immediate: true,
            }
        );

        // 分页改变
        const onPageNoChange = (page: number) => {
            router.push({ query: { pageNo: String(page) } });
        };

        return {
            loading,
            articleList,
            pageInfo,
            total,
            onPageNoChange,
        };
    },
});
</script>
