// app/vite-react19/src/views/Backend/Comment/Review.tsx
import { Image, Space, Table, Button, message, Modal } from "antd";
import { ColumnType, TablePaginationConfig } from "antd/es/table";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { NavLink } from "react-router-dom";
import { useAsyncLoading } from "@/hooks/async";
import { CommentDTO } from "@/bean/dto";
import CommentAvatarFallback from "@/assets/img/comment-avatar.svg";
import { format } from "@/utils/date-utils";
import { commentService } from "@/services/comment";
import { approvedFormatter } from "@/utils/formatter";

const Wrapper = styled.section`
    padding: 20px;
    background-color: #fff;
`;

const Avatar = styled(Image)`
    && {
        width: 40px;
        height: 40px;
        border-radius: 100%;
    }
`;

export const Component = () => {
    const [messageList, setMessageList] = useState<CommentDTO[]>([]);

    const [pagination, setPagination] = useState<TablePaginationConfig>({
        current: 1,
        pageSize: 10,
        total: 0,
        showTotal: (total) => `共计${total}条`,
        onChange: (page, pageSize) => {
            setPagination({ ...pagination, current: page, pageSize });
        },
    });

    const handleGetCommentList = async () => {
        const res = await commentService.pageNotApproved({
            pageNo: pagination.current as number,
            pageSize: pagination.pageSize as number,
            type: 1, // 1代表是文章评论
        });
        setMessageList(res.data);
        setPagination({ ...pagination, total: res.total });
    };

    const { loading, trigger: search } = useAsyncLoading(handleGetCommentList, [pagination.current, pagination.pageSize], {
        initialLoading: true,
    });

    useEffect(() => {
        search();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pagination.current, pagination.pageSize]);

    const onCommitReview = async (record: CommentDTO, approved: 1 | 2) => {
        Modal.confirm({
            title: `确认要执行${approved === 1 ? "通过" : "不通过"}操作吗？`,
            onOk: async () => {
                await commentService.review({
                    id: record.id,
                    approved,
                    email: record.email,
                    content: record.content,
                    jump_url: record.jump_url,
                });
                message.success("操作成功");
                search();
            },
        });
    };

    const columns: ColumnType<CommentDTO>[] = [
        {
            title: "昵称",
            width: "120px",
            dataIndex: "nick_name",
        },
        {
            title: "头像",
            dataIndex: "avatar",
            width: "132px",
            render: (_, record) => {
                return <Avatar src={record.avatar} fallback={CommentAvatarFallback} />;
            },
        },
        {
            title: "评论内容",
            dataIndex: "content",
            width: "180px",
        },
        {
            title: "评论的文章",
            dataIndex: "article_name",
            width: "180px",
            render: (_, record) => {
                return <NavLink to={`/article/${record.article_id}`}>{record.article_name}</NavLink>;
            },
        },
        {
            title: "审核状态",
            dataIndex: "approved",
            width: "120px",
            render: (_, record) => {
                return approvedFormatter(record.approved ?? 0);
            },
        },
        {
            title: "邮箱",
            dataIndex: "email",
            width: "140px",
        },
        {
            title: "个人网站",
            dataIndex: "site_url",
            width: "160px",
        },
        {
            title: "创建时间",
            dataIndex: "create_time",
            width: "160px",
            render: (value) => {
                return format(value);
            },
        },
        {
            title: "操作",
            width: "180px",
            key: "action",
            fixed: "right",
            render: (_, record) => {
                return (
                    <Space>
                        <Button type="primary" ghost size="small" onClick={() => onCommitReview(record, 1)}>
                            通过
                        </Button>

                        <Button type="primary" ghost size="small" danger onClick={() => onCommitReview(record, 2)}>
                            不通过
                        </Button>
                    </Space>
                );
            },
        },
    ];

    return (
        <Wrapper>
            <Table
                rowKey="id"
                dataSource={messageList}
                columns={columns}
                loading={loading}
                pagination={loading ? false : pagination}
                scroll={{ x: "max-content" }}
            ></Table>
        </Wrapper>
    );
};

// app/vite-vue3/src/views/backend/comment/review/index.vue
<!--
 * @author: Tusi
 * @description: 分页查询未审核的评论
-->
<template>
    <section class="admin-page-wrapper">
        <a-table
            row-key="id"
            :data-source="commentList"
            :columns="columns"
            :loading="loading"
            :scroll="{ x: 1500 }"
            :pagination="pagination"
        >
            <template #bodyCell="{ column, record }">
                <a-space v-if="column.key === 'action'">
                    <a-button size="small" type="primary" ghost @click="onCommitReview(record, 1)">通过</a-button>
                    <a-button size="small" danger ghost @click="onCommitReview(record, 2)">不通过</a-button>
                </a-space>
            </template>
        </a-table>
    </section>
</template>

<script lang="tsx" setup>
import { reactive, ref } from "vue";
import { message, Modal, Image } from "ant-design-vue";
import { RouterLink } from "vue-router";
import { CommentDTO } from "@/bean/dto";
import { useAsyncLoading } from "@/hooks/async";
import { commentService } from "@/services/comment";
import { format } from "@/utils/date-utils";
import { approvedFormatter } from "@/utils/formatter";
import CommentAvatarFallback from "@/assets/img/comment-avatar.svg";

const commentList = ref<CommentDTO[]>([]);

const pagination = reactive({
    current: 1,
    pageSize: 10,
    total: 0,
    showTotal: (total: number) => `共计${total}条`,
    onChange: (page: number) => {
        pagination.current = page;
        search();
    },
});

// 分页查询
const handleGetComments = async () => {
    const res = await commentService.pageNotApproved({
        type: 1, // 1代表评论
        pageNo: pagination.current,
        pageSize: pagination.pageSize,
    });
    commentList.value = res.data;
    pagination.total = res.total;
};

const { trigger: search, loading } = useAsyncLoading(handleGetComments);

// 直接调用
search();

// 提交审核
const onCommitReview = (record: CommentDTO, approved: 1 | 2) => {
    const action = approved === 1 ? "通过" : "不通过";
    Modal.confirm({
        title: `确认要执行${action}操作吗？`,
        onOk: async () => {
            await commentService.review({
                id: record.id,
                approved,
                email: record.email,
                content: record.content,
                jump_url: record.jump_url,
            });
            message.success("操作成功");
            search();
        },
    });
};

const columns = ref([
    {
        title: "昵称",
        width: "120px",
        dataIndex: "nick_name",
    },
    {
        title: "头像",
        width: "100px",
        dataIndex: "avatar",
        customRender: ({ text }: { text: string }) => {
            return <Image src={text || ""} fallback={CommentAvatarFallback} wrapperClassName="comment-avatar" />;
        },
    },
    {
        title: "评论内容",
        width: "180px",
        dataIndex: "content",
    },
    {
        title: "评论的文章",
        width: "180px",
        dataIndex: "article_name",
        customRender: ({ text, record }: { text: string; record: CommentDTO }) => {
            return <RouterLink to={`/article/${record.article_id}`}>{text}</RouterLink>;
        },
    },
    {
        title: "审核状态",
        width: "120px",
        dataIndex: "approved",
        customRender: ({ text }: { text: 1 | 0 }) => {
            return approvedFormatter(text);
        },
    },
    {
        title: "邮箱",
        width: "140px",
        dataIndex: "email",
    },
    {
        title: "个人网站",
        width: "160px",
        dataIndex: "site_url",
    },
    {
        title: "创建时间",
        width: "140px",
        dataIndex: "create_time",
        customRender: ({ text }: { text: string }) => {
            return format(text);
        },
    },
    {
        title: "操作",
        width: "180px",
        key: "action",
        fixed: "right",
    },
]);
</script>

<style lang="scss" scoped src="@/views/backend/styles/avatar.scss"></style>
