// app/cra-react18/src/views/Login/index.tsx
import styled from "styled-components";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "antd/es/form/Form";
import { Button, Form, Input, message } from "antd";
import { LockOutlined, UserOutlined } from "@ant-design/icons";
import Hashes from "jshashes";
import { validatorService } from "@/services/validator";
import { REQUIRED_VALIDATOR_BLUR } from "@/utils/validator";
import BaseLayout from "@/components/BaseLayout";
import { useAsyncLoading } from "@/hooks/async";
import { useAppDispatch } from "@/store/hooks";
import { dispatchLogin } from "@/store/slices/auth";
import { format } from "@/utils/date-utils";

const Wrapper = styled.section`
    position: relative;
    > h2 {
        text-align: center;
        font-size: 1.5em;
    }
`;

const verifyimgHeight = "30px";

const StyledForm = styled(Form)`
    width: 400px;
    max-width: 86%;
    margin: 0 auto;
`;

const CodeInput = styled(Input)`
    padding-right: 90px;

    .verify-code {
        position: absolute;
        right: 0;
        top: 0;
        height: ${verifyimgHeight};
        > svg {
            width: 90px;
            height: ${verifyimgHeight};
            line-height: ${verifyimgHeight};
        }
    }
`;

export const Component: React.FC = () => {
    const [svgHtml, setSvgHtml] = useState("");

    const navigate = useNavigate();

    const dispatch = useAppDispatch();

    const [form] = useForm();

    const rules = {
        userName: [REQUIRED_VALIDATOR_BLUR],
        password: [REQUIRED_VALIDATOR_BLUR],
        captcha: [REQUIRED_VALIDATOR_BLUR],
    };

    const getVerifyCode = async () => {
        const res = await validatorService.imgCode();
        setSvgHtml(res.data);
    };

    useEffect(() => {
        getVerifyCode();
    }, []);

    const handleLogin = async () => {
        await form.validateFields();
        const sha256 = new Hashes.SHA256();
        const params = {
            ...form.getFieldsValue(),
            password: sha256.hex(form.getFieldValue("password")),
        };
        try {
            const result = await dispatch(dispatchLogin(params)).unwrap();
            message.success(`登录成功，上次登录时间：${format(result.last_login_time)}`);
            navigate("/backend");
        } catch (error) {
            getVerifyCode();
        }
    };

    const { loading, trigger: onClickLogin } = useAsyncLoading(handleLogin);

    const handleKeyUp = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === "Enter") {
            onClickLogin();
        }
    };

    return (
        <BaseLayout>
            <Wrapper>
                <h2>登录后台</h2>
                <StyledForm form={form}>
                    <Form.Item name="userName" rules={rules.userName}>
                        <Input
                            placeholder="用户名"
                            prefix={<UserOutlined style={{ color: "rgba(0, 0, 0, 0.25)" }} />}
                            onKeyUp={handleKeyUp}
                        />
                    </Form.Item>
                    <Form.Item name="password" rules={rules.password}>
                        <Input
                            type="password"
                            placeholder="密码"
                            prefix={<LockOutlined style={{ color: "rgba(0, 0, 0, 0.25)" }} />}
                            onKeyUp={handleKeyUp}
                        />
                    </Form.Item>
                    <Form.Item name="captcha" rules={rules.captcha}>
                        <CodeInput
                            placeholder="验证码"
                            prefix={<LockOutlined style={{ color: "rgba(0, 0, 0, 0.25)" }} />}
                            suffix={<div className="verify-code" dangerouslySetInnerHTML={{ __html: svgHtml }} />}
                            onKeyUp={handleKeyUp}
                        />
                    </Form.Item>
                    <Form.Item className="text-center">
                        <Button type="primary" loading={loading} onClick={onClickLogin}>
                            登录
                        </Button>
                    </Form.Item>
                </StyledForm>
            </Wrapper>
        </BaseLayout>
    );
};

// app/webpack-vue3/src/views/login/index.vue
<!--
 * @author: Tusi
 * @description: 登录页
-->
<template>
    <base-layout>
        <section class="login-page__wrapper">
            <h2>登录后台</h2>
            <a-form class="form-login" ref="formRef" :model="formModel" :rules="rules" :wrapper-col="{ span: 24 }">
                <a-form-item name="userName">
                    <a-input v-model:value="formModel.userName" placeholder="用户名" @keyup.enter="onClickLogin">
                        <template #prefix><UserOutlined style="color: rgba(0, 0, 0, 0.25)" /></template>
                    </a-input>
                </a-form-item>
                <a-form-item name="password">
                    <a-input v-model:value="formModel.password" type="password" placeholder="密码" @keyup.enter="onClickLogin">
                        <template #prefix><LockOutlined style="color: rgba(0, 0, 0, 0.25)" /></template>
                    </a-input>
                </a-form-item>
                <a-form-item name="captcha">
                    <a-input class="input-code" v-model:value="formModel.captcha" placeholder="验证码" @keyup.enter="onClickLogin">
                        <template #prefix><LockOutlined style="color: rgba(0, 0, 0, 0.25)" /></template>
                        <template #suffix>
                            <div class="verify-code" v-html="svgHtml" @click="getVerifyCode"></div>
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item class="align-center">
                    <a-button type="primary" :loading="loading" @click="onClickLogin">登录</a-button>
                </a-form-item>
            </a-form>
        </section>
    </base-layout>
</template>

<script lang="ts">
import Hashes from "jshashes";
import { defineComponent, reactive, ref } from "vue";
import { UserOutlined, LockOutlined } from "@ant-design/icons-vue";
import { Form, Input, message } from "ant-design-vue";
import { useRouter } from "vue-router";
import { useStore } from "vuex";
import { REQUIRED_VALIDATOR_BLUR } from "@/utils/validator";
import { validatorService } from "@/services/validator";
import { format } from "@/utils/date-utils";
import { useAsyncLoading } from "@/hooks/async";
import { key } from "@/store";
import { LOGIN_ACTION } from "@/store/constants";

export default defineComponent({
    name: "Login",
    components: {
        UserOutlined,
        LockOutlined,
        [Form.name]: Form,
        [Form.Item.name]: Form.Item,
        [Input.name]: Input,
    },
    setup() {
        // vuex
        const store = useStore(key);
        // router
        const router = useRouter();

        const formRef = ref();

        const formModel = reactive({
            userName: "",
            password: "",
            captcha: "",
        });

        const rules = reactive({
            userName: [REQUIRED_VALIDATOR_BLUR],
            password: [REQUIRED_VALIDATOR_BLUR],
            captcha: [REQUIRED_VALIDATOR_BLUR],
        });

        // svg内容
        const svgHtml = ref("");

        // 获取验证码
        const getVerifyCode = async () => {
            const res = await validatorService.imgCode();

            svgHtml.value = res.data;
        };

        // 直接调用
        getVerifyCode();

        const handleLogin = async () => {
            await formRef.value.validate();
            const sha256 = new Hashes.SHA256();
            const params = {
                ...formModel,
                password: sha256.hex(formModel.password),
            };
            try {
                const userInfo = await store.dispatch(LOGIN_ACTION, params);
                message.success(`登录成功，上次登录时间：${format(userInfo.last_login_time)}`);
                router.push("/backend");
            } catch (error) {
                getVerifyCode();
            }
        };

        const { loading, trigger: onClickLogin } = useAsyncLoading(handleLogin);

        return {
            formRef,
            formModel,
            rules,
            onClickLogin,
            loading,
            svgHtml,
            getVerifyCode,
        };
    },
});
</script>

<style lang="scss" scoped>
.login-page__wrapper {
    position: relative;
    > h2 {
        text-align: center;
    }
}

:deep(.form-login) {
    width: 400px;
    max-width: 86%;
    margin: 0 auto;
}

:deep(.input-code) {
    padding-right: 90px;
}

$verifyimg-height: 30px;
.verify-code {
    position: absolute;
    right: 0;
    top: 0;
    height: $verifyimg-height;
    > :deep(svg) {
        width: 90px;
        height: $verifyimg-height;
        line-height: $verifyimg-height;
    }
}
</style>
