// app/vite-react19/src/views/Backend/Category/Edit.tsx
import { Form, Input, Image, Button, message } from "antd";
import { useWatch } from "antd/es/form/Form";
import { CategoryDTO } from "@fullstack-blog/types";
import { categoryService } from "@fullstack-blog/services";
import { useAsyncLoading } from "@/hooks/async";

const Edit: React.FC<{ row: CategoryDTO; onSuccess: () => void }> = ({ row, onSuccess }) => {
    const [form] = Form.useForm();

    const poster = useWatch("poster", form);

    const handleSave = async (values: { category_name: string; poster: string }) => {
        await categoryService.adminUpdate({
            ...values,
            id: row.id,
        });
        message.success("保存成功");
        onSuccess();
    };

    const { loading, trigger: onSave } = useAsyncLoading(handleSave, [row.id]);

    return (
        <Form
            wrapperCol={{ span: 24 }}
            form={form}
            labelCol={{ style: { width: "100px" } }}
            initialValues={{
                category_name: row.category_name,
                poster: row.poster,
            }}
            onFinish={onSave}
        >
            <Form.Item label="分类名称" name="category_name">
                <Input placeholder="请输入分类名称" />
            </Form.Item>
            <Form.Item label="海报">
                <Form.Item name="poster">
                    <Input placeholder="请输入海报" />
                </Form.Item>
                <Image src={poster} />
            </Form.Item>
            <Form.Item className="text-center">
                <Button type="primary" htmlType="submit" loading={loading}>
                    保存
                </Button>
            </Form.Item>
        </Form>
    );
};

export default Edit;

// app/vite-vue3/src/views/backend/category/edit.vue
<template>
    <a-form class="edit-form" ref="formRef" :model="formModel" :rules="rules" :wrapper-col="{ span: 24 }">
        <a-form-item label="分类名称" name="category_name">
            <a-input v-model:value="formModel.category_name" placeholder="请输入分类名称"></a-input>
        </a-form-item>
        <a-form-item label="海报" name="poster">
            <a-input v-model:value="formModel.poster" placeholder="请输入海报"></a-input>
            <div style="margin-top: 10px">
                <a-image :src="formModel.poster" />
            </div>
        </a-form-item>
        <a-form-item class="align-center">
            <a-button type="primary" :loading="loading" @click="onSave">保存</a-button>
        </a-form-item>
    </a-form>
</template>

<script lang="ts">
import { defineComponent, PropType, reactive } from "vue";
import { message } from "ant-design-vue";
import { REQUIRED_VALIDATOR_BLUR } from "@fullstack-blog/utils";
import { categoryService } from "@fullstack-blog/services";
import { CategoryDTO } from "@fullstack-blog/types";
import { useAsyncLoading } from "@/hooks/async";

export default defineComponent({
    props: {
        row: {
            type: Object as PropType<CategoryDTO>,
        },
    },
    emits: ["success"],
    setup(props, { emit }) {
        const row = props.row as CategoryDTO;
        const formModel = reactive({
            id: row.id,
            category_name: row.category_name,
            poster: row.poster,
        });

        const rules = {
            category_name: [REQUIRED_VALIDATOR_BLUR],
            poster: [REQUIRED_VALIDATOR_BLUR],
        };

        const handleSave = async () => {
            await categoryService.adminUpdate(formModel);
            message.success("保存成功");
            emit("success");
        };

        const { loading, trigger: onSave } = useAsyncLoading(handleSave);

        return {
            formModel,
            loading,
            rules,
            onSave,
        };
    },
});
</script>
