// app/vite-react19/src/views/Backend/index.tsx
import { Avatar, Dropdown, Layout, Menu } from "antd";
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import styled from "styled-components";
import { useEffect, useMemo, useState } from "react";
import { HomeOutlined, MenuFoldOutlined, MenuUnfoldOutlined } from "@ant-design/icons";
import { navs, flatNavs } from "./navs";
import logo from "@/assets/img/logo.png";
import { useAuthStore } from "@/store";

const StyledLayout = styled(Layout)`
    height: 100%;

    .logo {
        max-width: 80%;
        height: 32px;
        display: block;
        margin: 16px auto;
    }

    .trigger {
        padding: 0 24px;
    }
`;

const MainLayout = styled(Layout)`
    > .ant-layout-header {
        background: rgb(255, 255, 255);
        padding: 0;
        .anticon {
            font-size: 18px;
            transition: color 0.3s;
            &:hover {
                color: #1890ff;
            }
        }

        .admin-avatar {
            color: #1890ff;
            background-color: rgb(253, 227, 207);
            float: right;
            margin-right: 24px;
            margin-top: 16px;
        }
    }

    .ant-layout-content {
        padding: 20px;
        background-color: #f5f5f5;
        overflow: auto;
    }
`;

const Component = () => {
    const location = useLocation();

    const [menuOpenKeys, setMenuOpenKeys] = useState<string[]>([]);

    const [collapsed, setCollapsed] = useState(false);

    const selectedKeys = useMemo(() => [location.pathname], [location.pathname]);

    const navigate = useNavigate();

    const dispatchLogout = useAuthStore((state) => state.dispatchLogout);

    const calcOpenKeys = (): string[] => {
        const activeNav = flatNavs.find((item) => item.key === location.pathname);
        return (activeNav?.parentKeys as string[]) || [];
    };

    useEffect(() => {
        setMenuOpenKeys(collapsed ? [] : calcOpenKeys());
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [collapsed, location.pathname]);

    const toggleMenu = () => {
        const newCollapsed = !collapsed;
        setCollapsed(newCollapsed);
    };

    const onSiderCollapse = (collapsed: boolean) => {
        setCollapsed(collapsed);
    };

    const onClickMenu = ({ key }: { key: string }) => {
        navigate(key);
    };

    const handleDropdownMenuClick = async ({ key }: { key: string }) => {
        switch (key) {
            case "write":
                navigate("/backend/write");
                break;
            case "logout":
                await dispatchLogout();
                navigate("/");
                break;
            default:
                break;
        }
    };

    const goHome = () => {
        navigate("/");
    };

    return (
        <StyledLayout>
            <Layout.Sider trigger={null} collapsed={collapsed} collapsible breakpoint="lg" onCollapse={onSiderCollapse}>
                <img src={logo} className="logo" alt="logo" />
                <Menu
                    mode="inline"
                    theme="dark"
                    openKeys={menuOpenKeys}
                    selectedKeys={selectedKeys}
                    onOpenChange={(openKeys) => setMenuOpenKeys(openKeys)}
                    onClick={onClickMenu}
                >
                    {navs.map((sub) => (
                        <Menu.SubMenu
                            key={sub.key}
                            title={
                                <span>
                                    {sub.icon}
                                    <span>{sub.title}</span>
                                </span>
                            }
                        >
                            {sub.children.map((child) => (
                                <Menu.Item key={child.key}>{child.title}</Menu.Item>
                            ))}
                        </Menu.SubMenu>
                    ))}
                </Menu>
            </Layout.Sider>
            <MainLayout>
                <Layout.Header>
                    {collapsed ? (
                        <MenuUnfoldOutlined className="trigger" onClick={toggleMenu} />
                    ) : (
                        <MenuFoldOutlined className="trigger" onClick={toggleMenu} />
                    )}
                    <HomeOutlined onClick={goHome} />

                    <Dropdown
                        menu={{
                            items: [
                                { label: "开始创作", key: "write" },
                                { label: "退出登录", key: "logout" },
                            ],
                            onClick: handleDropdownMenuClick,
                        }}
                    >
                        <Avatar className="admin-avatar">T</Avatar>
                    </Dropdown>
                </Layout.Header>
                <Layout.Content>
                    <Outlet />
                </Layout.Content>
            </MainLayout>
        </StyledLayout>
    );
};

export default Component;

// app/vite-vue3/src/views/backend/index.vue
<template>
    <a-layout class="backend-layout">
        <a-layout-sider :trigger="null" v-model:collapsed="menuState.collapsed" collapsible breakpoint="lg" @collapse="onSiderCollapse">
            <img class="logo" src="@/assets/img/logo.png" />
            <a-menu theme="dark" mode="inline" v-model:openKeys="menuState.openKeys" :selected-keys="selectedKeys" @click="onClickMenu">
                <a-sub-menu v-for="sub in navs" :key="sub.key">
                    <template #title>
                        <span>
                            <component :is="sub.icon" />
                            <span>{{ sub.title }}</span>
                        </span>
                    </template>
                    <template #default>
                        <a-menu-item v-for="child in sub.children" :key="child.key">{{ child.title }}</a-menu-item>
                    </template>
                </a-sub-menu>
            </a-menu>
        </a-layout-sider>
        <a-layout>
            <a-layout-header class="right-header">
                <MenuUnfoldOutlined v-if="menuState.collapsed" class="trigger" @click="toggleMenu" />
                <MenuFoldOutlined v-else class="trigger" @click="toggleMenu" />
                <HomeOutlined @click="goHome" />

                <a-dropdown v-model:open="isDropdownVisible">
                    <a-avatar class="admin-avatar">T</a-avatar>

                    <template #overlay>
                        <a-menu @click="handleDropdownMenuClick">
                            <a-menu-item key="write">开始创作</a-menu-item>
                            <a-menu-item key="logout">退出登录</a-menu-item>
                        </a-menu>
                    </template>
                </a-dropdown>
            </a-layout-header>
            <a-layout-content class="right-main">
                <router-view />
            </a-layout-content>
        </a-layout>
    </a-layout>
</template>
<script lang="tsx">
import { MenuFoldOutlined, MenuUnfoldOutlined, HomeOutlined } from "@ant-design/icons-vue";
import { computed, defineComponent, reactive, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { tree2Arr } from "@/utils/tree";
import { NavItem, navs } from "./navs.tsx";
import { useAuthStore } from "@/stores/auth";

interface MenuState {
    collapsed: boolean;
    openKeys: Array<string>;
    preOpenKeys: Array<string>;
}

export default defineComponent({
    name: "Backend",
    components: {
        MenuFoldOutlined,
        MenuUnfoldOutlined,
        HomeOutlined,
    },
    setup() {
        const authStore = useAuthStore();

        const route = useRoute();
        const router = useRouter();

        // 菜单相关
        const flatNavs = tree2Arr<NavItem>(navs);

        const calcOpenKeys = () => {
            const activeNav = flatNavs.find((item) => item.key === route.path);
            return activeNav?.parentKeys || [];
        };

        const initOpenKeys = calcOpenKeys();

        // 菜单状态项
        const menuState = reactive<MenuState>({
            collapsed: false,
            openKeys: initOpenKeys,
            preOpenKeys: initOpenKeys,
        });

        // 监听openKeys的变化，记录preOpenKeys
        watch(
            () => menuState.openKeys,
            (_val, oldVal) => {
                menuState.preOpenKeys = oldVal;
            }
        );

        // 路由的变化会，需要更新openKeys
        watch(
            () => route.path,
            () => {
                menuState.openKeys = calcOpenKeys();
            }
        );

        // 手动收起/展开菜单
        const toggleMenu = () => {
            menuState.collapsed = !menuState.collapsed;
            menuState.openKeys = menuState.collapsed ? [] : menuState.preOpenKeys;
        };

        // 侧边收起和展开事件
        const onSiderCollapse = (collapsed: boolean) => {
            menuState.collapsed = collapsed;
            menuState.openKeys = menuState.collapsed ? [] : menuState.preOpenKeys;
        };

        const selectedKeys = computed(() => [route.path]);

        // 点击菜单
        const onClickMenu = ({ key }: { key: string }) => {
            router.push(key);
        };

        // 导航栏右侧信息
        const isDropdownVisible = ref(false);

        // 点击用户下拉菜单
        const handleDropdownMenuClick = async ({ key }: { key: string }) => {
            switch (key) {
                case "write":
                    router.push("/backend/write");
                    break;
                case "logout":
                    await authStore.dispatchLogout();
                    router.push("/");
                    break;
                default:
                    break;
            }
        };

        // 回到首页
        const goHome = () => {
            router.push("/");
        };

        return {
            selectedKeys,
            menuState,
            navs,
            toggleMenu,
            onSiderCollapse,
            onClickMenu,
            goHome,
            handleDropdownMenuClick,
            isDropdownVisible,
        };
    },
});
</script>

<style lang="scss" scoped>
.backend-layout {
    height: 100%;
}

.logo {
    max-width: 80%;
    height: 32px;
    display: block;
    margin: 16px auto;
}

.trigger {
    padding: 0 24px;
}

:deep(.right-header) {
    background: rgb(255, 255, 255);
    padding: 0;
    .anticon {
        font-size: 18px;
        transition: color 0.3s;
        &:hover {
            color: #1890ff;
        }
    }
    .admin-avatar {
        color: $color-primary;
        background-color: rgb(253, 227, 207);
        float: right;
        margin-right: 24px;
        margin-top: 16px;
    }
}

:deep(.right-main) {
    padding: 24px;
    flex: 1;
    overflow: auto;
}

:deep(.admin-page-wrapper) {
    padding: 20px;
    background: #fff;
}
</style>
