// app/vite-vue3/src/views/backend/category/index.vue
<template>
    <section class="admin-page-wrapper">
        <a-table
            row-key="id"
            :data-source="categoryList"
            :columns="columns"
            :loading="loading"
            :scroll="{ x: 1500 }"
            :pagination="pagination"
        >
            <template #bodyCell="{ column, record }">
                <a-space v-if="column.key === 'action'">
                    <a-button size="small" type="primary" ghost @click="onClickEdit(record)">编辑</a-button>
                    <a-button size="small" type="primary" ghost @click="onViewArticles(record)">分类下文章</a-button>
                </a-space>
            </template>
        </a-table>

        <a-modal title="编辑分类" v-model:open="isEditVisible" width="640px" :footer="null">
            <edit v-if="isEditVisible" :row="detailRow" @cancel="isEditVisible = false" @success="onEditSuccess" />
        </a-modal>
    </section>
</template>

<script lang="tsx" setup>
import { reactive, ref } from "vue";
import { Image } from "ant-design-vue";
import { useRouter } from "vue-router";
import { CategoryDTO } from "@/bean/dto";
import { categoryService } from "@/services/category";
import { useAsyncLoading } from "@/hooks/async";
import { format } from "@/utils/date-utils";
import LogoFallback from "@/assets/img/logo2.png";
import Edit from "./edit.vue";

const router = useRouter();

const categoryList = ref<CategoryDTO[]>([]);

const pagination = reactive({
    current: 1,
    pageSize: 10,
    total: 0,
    showTotal: (total: number) => `共计${total}条`,
    onChange: (page: number) => {
        pagination.current = page;
        search();
    },
});

// 分页查询
const handleGetCategorys = async () => {
    const res = await categoryService.adminPage({
        pageNo: pagination.current,
        pageSize: pagination.pageSize,
    });
    categoryList.value = res.data;
    pagination.total = res.total;
};

const { trigger: search, loading } = useAsyncLoading(handleGetCategorys);

// 直接调用
search();

const isEditVisible = ref(false);

const detailRow = ref<CategoryDTO>();

const onClickEdit = (record: CategoryDTO) => {
    detailRow.value = record;
    isEditVisible.value = true;
};

const onViewArticles = (record: CategoryDTO) => {
    router.push(`/category/${encodeURIComponent(record.category_name)}`);
};

const onEditSuccess = () => {
    isEditVisible.value = false;
    search();
};

const columns = ref([
    {
        title: "分类名称",
        width: "160px",
        dataIndex: "category_name",
        ellipsis: true,
        fixed: "left",
    },
    {
        title: "封面",
        width: "140px",
        dataIndex: "poster",
        customRender: ({ text }: { text: string }) => {
            return <Image class="category-poster" src={text} fallback={LogoFallback} />;
        },
    },
    {
        title: "文章数量",
        width: "120px",
        dataIndex: "article_count",
        ellipsis: true,
    },
    {
        title: "创建时间",
        width: "140px",
        dataIndex: "create_time",
        customRender: ({ text }: { text: string }) => {
            return format(text);
        },
    },
    {
        title: "更新时间",
        width: "140px",
        dataIndex: "update_time",
        customRender: ({ text }: { text: string }) => {
            return text ? format(text) : "-";
        },
    },
    {
        title: "操作",
        width: "200px",
        key: "action",
        fixed: "right",
    },
]);
</script>

<style lang="scss" scoped>
:deep(.ant-table-wrapper) {
    .category-poster {
        width: 160px;
        height: 92px;
        object-fit: contain;
    }
}
</style>

// app/cra-react18/src/views/Backend/Category/index.tsx
import { Image, Space, Table, Button, Modal } from "antd";
import { ColumnType, TablePaginationConfig } from "antd/es/table";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { NavLink } from "react-router-dom";
import Edit from "./Edit";
import { useAsyncLoading } from "@/hooks/async";
import { CategoryDTO } from "@/bean/dto";
import LogoFallback from "@/assets/img/logo2.png";
import { format } from "@/utils/date-utils";
import { categoryService } from "@/services/category";

const Wrapper = styled.section`
    padding: 20px;
    background-color: #fff;
`;

const StyledImage = styled(Image)`
    && {
        width: 160px;
        height: 72px;
        object-fit: cover;
    }
`;

export const Component = () => {
    const [categoryList, setCategoryList] = useState<CategoryDTO[]>([]);
    const [isEditVisible, setIsEditVisible] = useState(false);
    const [detailRow, setDetailRow] = useState<CategoryDTO>();

    const [pagination, setPagination] = useState<TablePaginationConfig>({
        current: 1,
        pageSize: 10,
        total: 0,
        showTotal: (total) => `共计${total}条`,
        onChange: (page, pageSize) => {
            setPagination({ ...pagination, current: page, pageSize });
        },
    });

    const handleGetCategoryList = async () => {
        const res = await categoryService.adminPage({
            pageNo: pagination.current as number,
            pageSize: pagination.pageSize as number,
        });
        setCategoryList(res.data);
        setPagination({ ...pagination, total: res.total });
    };

    const { loading, trigger: search } = useAsyncLoading(handleGetCategoryList, [pagination.current, pagination.pageSize], {
        initialLoading: true,
    });

    useEffect(() => {
        search();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pagination.current, pagination.pageSize]);

    const onClickEdit = (record: CategoryDTO) => {
        setDetailRow(record);
        setIsEditVisible(true);
    };

    const onEditSuccess = () => {
        setIsEditVisible(false);
        search();
    };

    const columns: ColumnType<CategoryDTO>[] = [
        {
            title: "分类名称",
            width: "120px",
            dataIndex: "category_name",
            ellipsis: true,
            fixed: "left",
        },
        {
            title: "封面",
            dataIndex: "poster",
            width: "192px",
            render: (_, record) => {
                return <StyledImage src={record.poster} fallback={LogoFallback} />;
            },
        },
        {
            title: "文章数量",
            dataIndex: "article_count",
            width: "100px",
            ellipsis: true,
        },
        {
            title: "创建时间",
            dataIndex: "create_time",
            width: "160px",
            render: (value) => {
                return format(value);
            },
        },
        {
            title: "更新时间",
            dataIndex: "update_time",
            width: "160px",
            render: (value) => {
                return value ? format(value) : "-";
            },
        },
        {
            title: "操作",
            width: "200px",
            key: "action",
            fixed: "right",
            render: (_, record, index) => {
                return (
                    <Space>
                        <Button type="primary" ghost size="small" onClick={() => onClickEdit(record)}>
                            编辑
                        </Button>
                        <NavLink to={`/category/${encodeURIComponent(record.category_name)}`}>
                            <Button type="primary" ghost size="small">
                                分类下文章
                            </Button>
                        </NavLink>
                    </Space>
                );
            },
        },
    ];

    return (
        <Wrapper>
            <Table
                rowKey="id"
                dataSource={categoryList}
                columns={columns}
                loading={loading}
                pagination={loading ? false : pagination}
                scroll={{ x: "max-content" }}
            ></Table>

            <Modal title="编辑分类" width="640px" footer={null} open={isEditVisible} onCancel={() => setIsEditVisible(false)}>
                {isEditVisible && detailRow && <Edit row={detailRow} onSuccess={onEditSuccess} />}
            </Modal>
        </Wrapper>
    );
};
