// app/cra-react18/src/App.tsx
import { RouterProvider } from "react-router-dom";
import { ConfigProvider, Skeleton } from "antd";
import { Provider } from "react-redux";
import { Suspense, useEffect } from "react";
import zhCN from "antd/locale/zh_CN";
import { store } from "./store";
import "dayjs/locale/zh-cn";
import { eventBus } from "./utils/eventbus";
import { router } from "./router";

function App() {
    useEffect(() => {
        const handleSessionInvalid = () => {
            router.navigate("/login");
        };

        eventBus.on("sessionInvalid", handleSessionInvalid);
        return () => {
            eventBus.off("sessionInvalid", handleSessionInvalid);
        };
    }, []);

    return (
        <Provider store={store}>
            <ConfigProvider
                locale={zhCN}
                theme={{
                    token: {
                        colorPrimary: "#008dff",
                        colorLink: "#87b4e2",
                        colorLinkHover: "#6d9ccd",
                    },
                }}
            >
                <Suspense fallback={<Skeleton />}>
                    <RouterProvider router={router} />
                </Suspense>
            </ConfigProvider>
        </Provider>
    );
}

export default App;

// app/vite-vue3/src/App.vue
<!--
 * @author: Tusi
 * @description: App
-->
<template>
    <a-config-provider
        :locale="zhCN"
        :theme="{
            token: {
                colorPrimary: '#008dff',
                colorLink: '#87b4e2',
            },
        }"
    >
        <section :class="{ 'hidden-x': isMenuVisible, 'is-admin': isAdmin }">
            <router-view :key="$route.path" />
        </section>
    </a-config-provider>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import zhCN from "ant-design-vue/es/locale/zh_CN";
import { useRoute } from "vue-router";
import { eventBus } from "./utils/eventbus";
import { useAuthStore } from "./stores/auth";
import { useGlobalUIState } from "./stores/global-ui-state";

const route = useRoute();

const { clearUserSession } = useAuthStore();

const { isMenuVisible } = useGlobalUIState();

const handleEvents = () => {
    eventBus.on("sessionInvalid", () => {
        clearUserSession();
    });
};

handleEvents();

const isAdmin = computed(() => route.meta.isAdmin as boolean);
</script>

<style lang="scss" scoped>
.hidden-x {
    overflow-x: hidden;
}
.is-admin {
    height: 100%;
}
</style>
