// app/cra-react18/src/views/Timeline/index.tsx
import { useEffect, useRef, useState } from "react";
import { Button, Card, Empty, Skeleton, Timeline } from "antd";
import { NavLink } from "react-router-dom";
import styled from "styled-components";
import { ArticleDTO } from "@/bean/dto";
import BaseLayout from "@/components/BaseLayout";
import { articleService } from "@/services/article";
import { format } from "@/utils/date-utils";
import { useAsyncLoading } from "@/hooks/async";
import LazyImage from "@/components/LazyImage";
import BottomTips from "@/components/BottomTips";

const StyledTimeline = styled(Timeline)`
    .timeline-card {
        border: 0;
        box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);

        .ant-card-body {
            display: flex;
            padding: 10px;
        }
    }
    ${LazyImage} {
        width: 80px;
        height: 60px;
        object-fit: cover;
    }

    .timeline-card__info {
        flex: 1;
        margin-left: 10px;
        font-size: 12px;
        overflow: hidden;

        > time {
            color: #999;
        }

        > h4 {
            margin: 3px 0;
            font-size: 14px;
            line-height: 1.2em;
        }

        .category {
            font-weight: 700;

            &:hover {
                color: #87b4e2;
                opacity: 0.85;
            }

            + .category::before {
                content: ", ";
            }
        }
    }
`;

export const Component: React.FC = () => {
    const [articleList, setArticleList] = useState<ArticleDTO[]>([]);

    const [pageInfo, setPageInfo] = useState({
        pageNo: 1,
        pageSize: 6,
    });

    const prevPageNo = useRef(pageInfo.pageNo);

    const [total, setTotal] = useState(0);

    const handleGetArticleList = async (isLoadMore = false) => {
        const res = await articleService.page(pageInfo);
        const mappedData = res.data.map((item) => {
            return {
                ...item,
                create_time: format(item.create_time),
            };
        });
        if (isLoadMore) {
            setArticleList([...articleList, ...mappedData]);
        } else {
            setArticleList(mappedData);
        }
        setTotal(res.total);
    };

    const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList, [pageInfo]);

    useEffect(() => {
        const isChangePage = pageInfo.pageNo !== prevPageNo.current;
        getPageList(isChangePage);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pageInfo.pageNo]);

    useEffect(() => {
        prevPageNo.current = pageInfo.pageNo;
    }, [pageInfo.pageNo]);

    const loadMore = () => {
        if (articleList.length < total) {
            setPageInfo({ ...pageInfo, pageNo: pageInfo.pageNo + 1 });
        }
    };

    return (
        <BaseLayout>
            <>
                {articleList.length ? (
                    <StyledTimeline>
                        {articleList.map((article) => (
                            <Timeline.Item key={article.id} color="#2b82a8">
                                <Card className="timeline-card">
                                    <NavLink to={`/article/${article.id}`}>
                                        <LazyImage src={article.poster} />
                                    </NavLink>
                                    <div className="timeline-card__info">
                                        <time>{article.create_time}</time>
                                        <h4 className="truncate" title={article.article_name}>
                                            {article.article_name}
                                        </h4>
                                        {article.categories.map((category) => (
                                            <NavLink
                                                className="category"
                                                key={category.id}
                                                to={`/category/${encodeURIComponent(category.categoryName)}`}
                                            >
                                                <span>{category.categoryName}</span>
                                            </NavLink>
                                        ))}
                                    </div>
                                </Card>
                            </Timeline.Item>
                        ))}
                    </StyledTimeline>
                ) : null}

                {!articleList.length && !loading ? <Empty /> : null}

                <Skeleton loading={loading} active paragraph={{ rows: 6 }} />

                <BottomTips>
                    {articleList.length < total ? (
                        <Button shape="round" type="primary" onClick={loadMore}>
                            加载更多
                        </Button>
                    ) : (
                        <span>没有更多了</span>
                    )}
                </BottomTips>
            </>
        </BaseLayout>
    );
};

// app/webpack-vue3/src/views/timeline/index.vue
<!--
 * @author: Tusi
 * @description: 时间轴
-->
<template>
    <base-layout>
        <template v-if="articleList.length > 0">
            <a-timeline>
                <a-timeline-item v-for="article in articleList" :key="article.id" color="#2b82a8">
                    <router-link :to="`/article/${article.id}`">
                        <a-card class="timeline-card">
                            <el-image :src="article.poster" class="timeline-card__poster" fit="cover" lazy />
                            <div class="timeline-card__info">
                                <time>{{ article.formattedCreateTime }}</time>
                                <h4 class="ellipsis" :title="article.article_name">{{ article.article_name }}</h4>
                                <router-link
                                    v-for="category in article.categories"
                                    :key="category.id"
                                    :to="{ name: 'Category', params: { name: category.categoryName } }"
                                    class="category"
                                >
                                    <span>{{ category.categoryName }}</span>
                                </router-link>
                            </div>
                        </a-card>
                    </router-link>
                </a-timeline-item>
            </a-timeline>
        </template>

        <template v-else-if="!loading">
            <a-empty />
        </template>

        <a-skeleton :loading="loading" active :paragraph="{ rows: 6 }" />

        <bottom-tips>
            <a-button shape="round" type="primary" @click="loadMore" v-if="articleList.length < total">加载更多</a-button>
            <span v-else>没有更多了</span>
        </bottom-tips>
    </base-layout>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from "vue";
import { Card, Timeline } from "ant-design-vue";
import { ArticleDTO } from "@/bean/dto";
import { articleService } from "@/services/article";
import { useAsyncLoading } from "@/hooks/async";
import { format } from "@/utils/date-utils";

export default defineComponent({
    name: "Timeline",
    components: {
        [Timeline.name]: Timeline,
        [Timeline.Item.name]: Timeline.Item,
        [Card.name]: Card,
    },
    setup() {
        const articleList = ref<ArticleDTO[]>([]);

        const pageInfo = reactive({
            pageNo: 1,
            pageSize: 6,
        });

        const total = ref(0);

        const handleGetArticleList = async (isLoadMore = false) => {
            const res = await articleService.page(pageInfo);
            const mappedData = res.data.map((item) => {
                return {
                    ...item,
                    formattedCreateTime: format(item.create_time),
                };
            });
            if (isLoadMore) {
                articleList.value = [...articleList.value, ...mappedData];
            } else {
                articleList.value = mappedData;
            }
            total.value = res.total;
        };

        const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList);

        getPageList();

        // 分页改变
        const loadMore = () => {
            if (articleList.value.length < total.value) {
                pageInfo.pageNo++;
                getPageList(true);
            }
        };

        return {
            loading,
            articleList,
            pageInfo,
            total,
            loadMore,
        };
    },
});
</script>

<style lang="scss" scoped>
:deep(.timeline-card) {
    border: 0;
    box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);

    .ant-card-body {
        display: flex;
        padding: 10px;
    }

    .timeline-card__poster {
        width: 80px;
        height: 60px;
    }

    .timeline-card__info {
        flex: 1;
        margin-left: 10px;
        font-size: 12px;
        overflow: hidden;

        > time {
            color: #999;
        }

        > h4 {
            margin: 3px 0;
            font-size: 14px;
            line-height: 1.2em;
        }

        .category {
            font-weight: 700;

            + .category::before {
                content: ", ";
            }
        }
    }
}

.no-more {
    font-size: 14px;
    color: #999;
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    margin-top: -6px;
}
</style>
