// app/cra-react18/src/views/Tags/index.tsx
import { useCallback, useEffect, useState } from "react";
import { Badge, Empty, Skeleton, Tag } from "antd";
import { NavLink } from "react-router-dom";
import styled, { css } from "styled-components";
import { TagDTO } from "@/bean/dto";
import { useAsyncLoading } from "@/hooks/async";
import BaseLayout from "@/components/BaseLayout";
import { tagService } from "@/services/tag";

const StyledTag = styled(Tag)`
    margin-top: 10px;
    padding: 4px 8px;
    font-size: 16px;
    cursor: pointer;
    > span {
        vertical-align: middle;
    }
    .ant-badge {
        margin-right: 6px;
    }
    .ant-badge-count {
        background: #348ba9;
    }
`;

const mainCss = css`
    padding: 24px 18px;
    background-color: #f5f5f5;
    @media screen and (min-width: 992px) {
        background-color: transparent;
    }
`;

export const Component: React.FC = () => {
    const [tagList, setTagList] = useState<TagDTO[]>([]);

    const handleGetTagList = useCallback(async () => {
        const { data } = await tagService.all({ getCount: "1" });
        setTagList(data);
    }, []);

    const { trigger: getTagList, loading } = useAsyncLoading(handleGetTagList);

    useEffect(() => {
        getTagList();
    }, [getTagList]);

    return (
        <BaseLayout mainCss={mainCss}>
            <h2 style={{ marginBottom: "16px", fontSize: "24px", textAlign: "center" }}>文章标签</h2>

            <Skeleton loading={loading} active={true} paragraph={{ rows: 12 }}>
                {tagList.length > 0 ? (
                    tagList.map((tag) => {
                        return (
                            <NavLink key={tag.id} to={`/tag/${encodeURIComponent(tag.tag_name)}`}>
                                <StyledTag icon={<Badge count={tag.tag_count}></Badge>}>{tag.tag_name}</StyledTag>
                            </NavLink>
                        );
                    })
                ) : (
                    <Empty />
                )}
            </Skeleton>
        </BaseLayout>
    );
};

// app/vite-vue3/src/views/tags/index.vue
<!--
 * @author: Tusi
 * @description: 所有标签
-->
<template>
    <base-layout>
        <h2>文章标签</h2>

        <a-skeleton :loading="loading" active :paragraph="{ rows: 12 }">
            <template v-if="tagList.length > 0">
                <router-link v-for="tag in tagList" :key="tag.id" :to="`/tag/${encodeURIComponent(tag.tag_name)}`">
                    <a-tag class="tagtag">
                        <template #icon>
                            <a-badge :count="tag.tag_count" />
                        </template>
                        {{ tag.tag_name }}
                    </a-tag>
                </router-link>
            </template>

            <template v-else>
                <a-empty />
            </template>
        </a-skeleton>
    </base-layout>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { TagDTO } from "@/bean/dto";
import { tagService } from "@/services/tag";
import { useAsyncLoading } from "@/hooks/async";

const tagList = ref<TagDTO[]>([]);

const handleGetAllTag = async () => {
    const res = await tagService.all({ getCount: true });
    tagList.value = res.data;
};

const { trigger: getTagList, loading } = useAsyncLoading(handleGetAllTag);

// 初始化直接调用接口
getTagList();
</script>

<style lang="scss" scoped>
:deep(.base-layout__main) {
    padding: 24px 18px;
    background-color: #f5f5f5;
}
:deep(.card-hot) {
    margin: 24px 18px;
}
h2 {
    margin: 0;
    text-align: center;
}
:deep(.tagtag) {
    margin-top: 10px;
    padding: 4px 8px;
    font-size: 16px;
    cursor: pointer;
    > span {
        vertical-align: middle;
    }
    .ant-badge-count {
        background: #348ba9;
    }
}

@media screen and (min-width: 992px) {
    :deep(.base-layout__main) {
        background-color: transparent;
    }
}
</style>
