// app/vite-react19/src/views/Home/index.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Empty, Pagination, Skeleton } from "antd";
import BaseLayout from "@/components/BaseLayout";
import { ArticleDTO } from "@fullstack-blog/types";
import { articleService } from "@fullstack-blog/services";
import { setScrollTop } from "@fullstack-blog/utils";
import { useAsyncLoading } from "@/hooks/async";
import CardArticle from "@/components/CardArticle";

const Home: React.FC = () => {
    const [articleList, setArticleList] = useState<ArticleDTO[]>([]);

    const [total, setTotal] = useState(0);

    const [searchParams, setSearchParams] = useSearchParams();

    const qsPageNo = searchParams.get("pageNo");
    const pageNo = qsPageNo ? Number(qsPageNo) : 1;

    const fetchParams = useMemo(
        () => ({
            pageNo,
            pageSize: 6,
        }),
        [pageNo],
    );

    const prevPageNo = useRef(pageNo);

    const handleGetArticleList = async (isChangePage: boolean) => {
        const { data, total } = await articleService.page(fetchParams);
        setArticleList(data);
        setTotal(total);
        if (isChangePage) {
            setScrollTop({
                useAnimation: true,
                duration: 0.3,
            });
        }
    };

    const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList, [fetchParams], { initialLoading: true });

    useEffect(() => {
        const isChangePage = fetchParams.pageNo !== prevPageNo.current;
        getPageList(isChangePage);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [fetchParams]);

    useEffect(() => {
        prevPageNo.current = fetchParams.pageNo;
    }, [fetchParams]);

    // 分页改变
    const onPageNoChange = (page: number) => {
        setSearchParams({ pageNo: String(page) });
    };

    return (
        <BaseLayout>
            <Skeleton loading={loading} active={true} paragraph={{ rows: 12 }}>
                {articleList.length > 0 ? (
                    <>
                        <section>
                            {articleList.map((article) => (
                                <CardArticle article={article} key={article.id} />
                            ))}
                        </section>

                        <Pagination
                            current={fetchParams.pageNo}
                            pageSize={fetchParams.pageSize}
                            total={total}
                            showLessItems={true}
                            simple={true}
                            showSizeChanger={false}
                            onChange={onPageNoChange}
                            className="mt-5 justify-center"
                        />
                    </>
                ) : (
                    <Empty />
                )}
            </Skeleton>
        </BaseLayout>
    );
};

export default Home;

// app/webpack-vue3/src/views/home/index.vue
<!--
 * @author: Tusi
 * @description: 首页
-->
<template>
    <base-layout>
        <a-skeleton :loading="loading" active :paragraph="{ rows: 12 }">
            <template v-if="articleList.length > 0">
                <section class="article-list">
                    <card-article v-for="article in articleList" :key="article.id" :article="article" />
                </section>

                <a-pagination
                    class="pagination-common"
                    v-model:current="pageInfo.pageNo"
                    v-model:pageSize="pageInfo.pageSize"
                    :total="total"
                    show-less-items
                    simple
                    @change="onPageNoChange"
                />
            </template>

            <template v-else>
                <a-empty />
            </template>
        </a-skeleton>
    </base-layout>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, watch } from "vue";
import { LocationQuery, useRoute, useRouter } from "vue-router";
import { ArticleDTO } from "@fullstack-blog/types";
import { articleService } from "@fullstack-blog/services";
import { useAsyncLoading } from "@/hooks/async";
import CardArticle from "@/components/card/card-article.vue";
import { setScrollTop } from "@fullstack-blog/utils";

export default defineComponent({
    name: "Home",
    components: {
        CardArticle,
    },
    setup() {
        // route
        const route = useRoute();
        const router = useRouter();

        const articleList = ref<ArticleDTO[]>([]);

        const pageInfo = reactive({
            pageNo: 1,
            pageSize: 6,
        });

        const total = ref(0);

        const handleGetArticleList = async (isChangePage: boolean) => {
            const res = await articleService.page(pageInfo);
            articleList.value = res.data;
            total.value = res.total;
            if (isChangePage) {
                setScrollTop({
                    useAnimation: true,
                    duration: 0.3,
                });
            }
        };

        const { trigger: getPageList, loading } = useAsyncLoading(handleGetArticleList);

        // 监听路由变化调用查询
        watch(
            () => route.query,
            (val: LocationQuery, oldVal) => {
                const { pageNo } = val;
                if (pageNo) {
                    pageInfo.pageNo = Number(pageNo);
                } else {
                    pageInfo.pageNo = 1;
                }
                const isChangePage = pageNo !== oldVal?.pageNo;
                getPageList(isChangePage);
            },
            {
                immediate: true,
            },
        );

        // 分页改变
        const onPageNoChange = (page: number) => {
            router.push({ query: { pageNo: String(page) } });
        };

        return {
            loading,
            articleList,
            pageInfo,
            total,
            onPageNoChange,
        };
    },
});
</script>
