// app/webpack-vue3/src/views/backend/msg/all/index.vue
<!--
 * @author: Tusi
 * @description: 所有留言
-->
<template>
    <section class="admin-page-wrapper">
        <a-table
            row-key="id"
            :data-source="messageList"
            :columns="columns"
            :loading="loading"
            :scroll="{ x: 1500 }"
            :pagination="pagination"
        >
            <template #bodyCell="{ column, record }">
                <a-space v-if="column.key === 'action'">
                    <a-button size="small" :type="record.deleted == 1 ? 'primary' : 'danger'" ghost @click="onClickLogicDel(record)">{{
                        record.deleted == 1 ? "逻辑恢复" : "逻辑删除"
                    }}</a-button>
                    <a-button size="small" type="danger" ghost @click="onClickDel(record)">物理删除</a-button>
                </a-space>
            </template>
        </a-table>
    </section>
</template>

<script lang="tsx">
import { defineComponent, reactive, ref } from "vue";
import { message, Modal, Image } from "ant-design-vue";
import { CommentDTO } from "@/bean/dto";
import { useAsyncLoading } from "@/hooks/async";
import { commentService } from "@/services/comment";
import { format } from "@/utils/date-utils";
import { approvedFormatter } from "@/utils/formatter";
import CommentAvatarFallback from "@/assets/img/comment-avatar.svg";

export default defineComponent({
    name: "AllMessage",
    setup() {
        const messageList = ref<CommentDTO[]>([]);

        const pagination = reactive({
            current: 1,
            pageSize: 10,
            total: 0,
            showTotal: (total: number) => `共计${total}条`,
            onChange: (page: number) => {
                pagination.current = page;
                search();
            },
        });

        // 分页查询
        const handleGetMessages = async () => {
            const res = await commentService.pageAdmin({
                pageNo: pagination.current,
                pageSize: pagination.pageSize,
                type: 2, // 2代表是留言
            });
            messageList.value = res.data;
            pagination.total = res.total;
        };

        const { trigger: search, loading } = useAsyncLoading(handleGetMessages);

        // 直接调用
        search();

        // 处理逻辑删除
        const onClickLogicDel = (record: CommentDTO) => {
            const isDeleted = record.deleted === 1;
            Modal.confirm({
                title: `确认要执行${isDeleted ? "逻辑恢复" : "逻辑删除"}吗？`,
                onOk: async () => {
                    await commentService.update({
                        id: record.id,
                        deleted: isDeleted ? 0 : 1,
                    });
                    message.success("操作成功");
                    search();
                },
            });
        };

        // 处理物理删除
        const onClickDel = (record: CommentDTO) => {
            Modal.confirm({
                title: "确认要删除吗？",
                onOk: async () => {
                    await commentService.delete(record.id);
                    message.success("操作成功");
                    pagination.current = 1;
                    search();
                },
            });
        };

        const columns = ref([
            {
                title: "昵称",
                width: "120px",
                dataIndex: "nick_name",
            },
            {
                title: "头像",
                width: "100px",
                dataIndex: "avatar",
                customRender: ({ text }: { text: string }) => {
                    return <Image src={text || ""} fallback={CommentAvatarFallback} wrapperClassName="comment-avatar" />;
                },
            },
            {
                title: "留言内容",
                width: "180px",
                dataIndex: "content",
            },
            {
                title: "审核状态",
                width: "120px",
                dataIndex: "approved",
                customRender: ({ text }: { text: 1 | 0 }) => {
                    return approvedFormatter(text);
                },
            },
            {
                title: "邮箱",
                width: "140px",
                dataIndex: "email",
            },
            {
                title: "个人网站",
                width: "160px",
                dataIndex: "site_url",
            },
            {
                title: "创建时间",
                width: "140px",
                dataIndex: "create_time",
                customRender: ({ text }: { text: string }) => {
                    return format(text);
                },
            },
            {
                title: "操作",
                width: "180px",
                key: "action",
                fixed: "right",
            },
        ]);

        return {
            messageList,
            columns,
            loading,
            onClickLogicDel,
            onClickDel,
            pagination,
        };
    },
});
</script>

<style lang="scss" scoped src="@/views/backend/styles/avatar.scss"></style>

// app/vite-react19/src/views/Backend/Message/All.tsx
import { Image, Space, Table, Button, message, Modal } from "antd";
import { ColumnType, TablePaginationConfig } from "antd/es/table";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { useAsyncLoading } from "@/hooks/async";
import { CommentDTO } from "@/bean/dto";
import CommentAvatarFallback from "@/assets/img/comment-avatar.svg";
import { format } from "@/utils/date-utils";
import { commentService } from "@/services/comment";
import { approvedFormatter } from "@/utils/formatter";

const Wrapper = styled.section`
    padding: 20px;
    background-color: #fff;
`;

const Avatar = styled(Image)`
    && {
        width: 40px;
        height: 40px;
        border-radius: 100%;
    }
`;

export const Component = () => {
    const [messageList, setMessageList] = useState<CommentDTO[]>([]);

    const [pagination, setPagination] = useState<TablePaginationConfig>({
        current: 1,
        pageSize: 10,
        total: 0,
        showTotal: (total) => `共计${total}条`,
        onChange: (page, pageSize) => {
            setPagination({ ...pagination, current: page, pageSize });
        },
    });

    const handleGetArticleList = async () => {
        const res = await commentService.pageAdmin({
            pageNo: pagination.current as number,
            pageSize: pagination.pageSize as number,
            type: 2, // 2代表是留言
        });
        setMessageList(res.data);
        setPagination({ ...pagination, total: res.total });
    };

    const { loading, trigger: search } = useAsyncLoading(handleGetArticleList, [pagination.current, pagination.pageSize], {
        initialLoading: true,
    });

    useEffect(() => {
        search();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pagination.current, pagination.pageSize]);

    const onClickLogicDel = async (record: CommentDTO) => {
        const isDeleted = record.deleted === 1;
        Modal.confirm({
            title: `确认要执行${isDeleted ? "逻辑恢复" : "逻辑删除"}吗？`,
            onOk: async () => {
                await commentService.update({
                    id: record.id,
                    deleted: isDeleted ? 0 : 1,
                });
                message.success("操作成功");
                search();
            },
        });
    };

    const onClickDel = async (record: CommentDTO) => {
        Modal.confirm({
            title: "确认要删除吗？",
            onOk: async () => {
                await commentService.delete(record.id);
                message.success("操作成功");
                if (pagination.current === 1) {
                    search();
                } else {
                    setPagination({ ...pagination, current: 1 });
                }
            },
        });
    };

    const columns: ColumnType<CommentDTO>[] = [
        {
            title: "昵称",
            width: "120px",
            dataIndex: "nick_name",
        },
        {
            title: "头像",
            dataIndex: "avatar",
            width: "132px",
            render: (_, record) => {
                return <Avatar src={record.avatar} fallback={CommentAvatarFallback} />;
            },
        },
        {
            title: "留言内容",
            dataIndex: "content",
            width: "180px",
        },
        {
            title: "审核状态",
            dataIndex: "approved",
            width: "120px",
            render: (_, record) => {
                return approvedFormatter(record.approved ?? 0);
            },
        },
        {
            title: "邮箱",
            dataIndex: "email",
            width: "140px",
        },
        {
            title: "个人网站",
            dataIndex: "site_url",
            width: "160px",
        },
        {
            title: "创建时间",
            dataIndex: "create_time",
            width: "160px",
            render: (value) => {
                return format(value);
            },
        },
        {
            title: "更新时间",
            dataIndex: "update_time",
            width: "160px",
            render: (value) => {
                return value ? format(value) : "-";
            },
        },
        {
            title: "操作",
            width: "180px",
            key: "action",
            fixed: "right",
            render: (_, record) => {
                return (
                    <Space>
                        <Button type="primary" ghost size="small" danger={record.deleted !== 1} onClick={() => onClickLogicDel(record)}>
                            {record.deleted === 1 ? "逻辑恢复" : "逻辑删除"}
                        </Button>

                        <Button type="primary" ghost size="small" onClick={() => onClickDel(record)}>
                            物理删除
                        </Button>
                    </Space>
                );
            },
        },
    ];

    return (
        <Wrapper>
            <Table
                rowKey="id"
                dataSource={messageList}
                columns={columns}
                loading={loading}
                pagination={loading ? false : pagination}
                scroll={{ x: "max-content" }}
            ></Table>
        </Wrapper>
    );
};
