// app/vite-vue3/src/views/backend/tag/index.vue
<template>
    <section class="admin-page-wrapper">
        <a-table row-key="id" :data-source="tagList" :columns="columns" :loading="loading" :scroll="{ x: 1500 }" :pagination="pagination">
            <template #bodyCell="{ column, record }">
                <a-space v-if="column.key === 'action'">
                    <a-button size="small" type="primary" ghost @click="onViewArticles(record)">标签下文章</a-button>
                </a-space>
            </template>
        </a-table>
    </section>
</template>

<script lang="tsx" setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { format } from "@fullstack-blog/utils";
import { tagService } from "@fullstack-blog/services";
import { TagDTO } from "@fullstack-blog/types";
import { useAsyncLoading } from "@/hooks/async";

const router = useRouter();

const tagList = ref<TagDTO[]>([]);

const pagination = reactive({
    current: 1,
    pageSize: 10,
    total: 0,
    showTotal: (total: number) => `共计${total}条`,
    onChange: (page: number) => {
        pagination.current = page;
        search();
    },
});

// 分页查询
const handleGetTags = async () => {
    const res = await tagService.adminPage({
        pageNo: pagination.current,
        pageSize: pagination.pageSize,
    });
    tagList.value = res.data;
    pagination.total = res.total;
};

const { trigger: search, loading } = useAsyncLoading(handleGetTags);

// 直接调用
search();

const onViewArticles = (record: TagDTO) => {
    router.push(`/tag/${encodeURIComponent(record.tag_name)}`);
};

const columns = ref([
    {
        title: "标签名称",
        width: "160px",
        dataIndex: "tag_name",
        ellipsis: true,
        fixed: "left",
    },
    {
        title: "文章数量",
        width: "120px",
        dataIndex: "article_count",
        ellipsis: true,
    },
    {
        title: "创建时间",
        width: "140px",
        dataIndex: "create_time",
        customRender: ({ text }: { text: string }) => {
            return format(text);
        },
    },
    {
        title: "更新时间",
        width: "140px",
        dataIndex: "update_time",
        customRender: ({ text }: { text: string }) => {
            return text ? format(text) : "-";
        },
    },
    {
        title: "操作",
        width: "120px",
        key: "action",
        fixed: "right",
    },
]);
</script>

<style lang="scss" scoped>
:deep(.ant-table-wrapper) {
    .category-poster {
        width: 160px;
        height: 92px;
        object-fit: contain;
    }
}
</style>

// app/cra-react18/src/views/Backend/Tag/index.tsx
import { Space, Table, Button } from "antd";
import { ColumnType, TablePaginationConfig } from "antd/es/table";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { NavLink } from "react-router-dom";
import { tagService } from "@fullstack-blog/services";
import { TagDTO } from "@fullstack-blog/types";
import { format } from "@fullstack-blog/utils";
import { useAsyncLoading } from "@/hooks/async";

const Wrapper = styled.section`
    padding: 20px;
    background-color: #fff;
`;

export const Component = () => {
    const [tagList, setTagList] = useState<TagDTO[]>([]);

    const [pagination, setPagination] = useState<TablePaginationConfig>({
        current: 1,
        pageSize: 10,
        total: 0,
        showTotal: (total) => `共计${total}条`,
        onChange: (page, pageSize) => {
            setPagination({ ...pagination, current: page, pageSize });
        },
    });

    const handleGetTagList = async () => {
        const res = await tagService.adminPage({
            pageNo: pagination.current as number,
            pageSize: pagination.pageSize as number,
        });
        setTagList(res.data);
        setPagination({ ...pagination, total: res.total });
    };

    const { loading, trigger: search } = useAsyncLoading(handleGetTagList, [pagination.current, pagination.pageSize], {
        initialLoading: true,
    });

    useEffect(() => {
        search();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pagination.current, pagination.pageSize]);

    const columns: ColumnType<TagDTO>[] = [
        {
            title: "标签名称",
            width: "120px",
            dataIndex: "tag_name",
            ellipsis: true,
            fixed: "left",
        },
        {
            title: "文章数量",
            dataIndex: "article_count",
            width: "100px",
            ellipsis: true,
        },
        {
            title: "创建时间",
            dataIndex: "create_time",
            width: "160px",
            render: (value) => {
                return format(value);
            },
        },
        {
            title: "更新时间",
            dataIndex: "update_time",
            width: "160px",
            render: (value) => {
                return value ? format(value) : "-";
            },
        },
        {
            title: "操作",
            width: "120px",
            key: "action",
            fixed: "right",
            render: (_, record, index) => {
                return (
                    <Space>
                        <NavLink to={`/tag/${encodeURIComponent(record.tag_name)}`}>
                            <Button type="primary" ghost size="small">
                                标签下文章
                            </Button>
                        </NavLink>
                    </Space>
                );
            },
        },
    ];

    return (
        <Wrapper>
            <Table
                rowKey="id"
                dataSource={tagList}
                columns={columns}
                loading={loading}
                pagination={loading ? false : pagination}
                scroll={{ x: "max-content" }}
            ></Table>
        </Wrapper>
    );
};
