// app/cra-react18/src/components/Comments/index.tsx
import { Button, Empty, Input, InputRef, message, Modal, Skeleton } from "antd";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";
import styled from "styled-components";
import DOMPurify from "dompurify";
import CardComment from "../CardComment";
import BottomTips from "../BottomTips";
import CommentUserInfoForm from "../CommentUserInfoForm";
import { useScrollBottom } from "@/hooks/scroll";
import { useAsyncLoading } from "@/hooks/async";
import { CommentDTO } from "@/bean/dto";
import { commentService } from "@/services/comment";
import { useAppSelector } from "@/store/hooks";
import { selectCommentUserInfo } from "@/store/slices/auth";

interface CommentsProps {
    articleId?: number;
    topic?: string;
    autoLoad?: boolean;
    placeTop?: boolean;
}

const CommentsWrapper = styled.div`
    display: flex;
    flex-direction: column;
    flex: 1;

    .comments__body {
        overflow: auto;
        flex: 1;
        padding: 20px;
    }

    .comments__list {
        > li + li {
            margin-top: 20px;
        }
    }

    .leave-comment {
        display: flex;
        align-items: center;
        padding: 12px 20px;
        box-shadow: 0 -1px 10px 0 rgba(0, 0, 0, 0.1);
        z-index: 2;
    }
`;

const ButtonCreate = styled(Button)`
    margin: 20px auto;
    display: block;
`;

export type CommentsRef = {
    showEditUserInfoForm: () => void;
};

const Comments = forwardRef<CommentsRef, CommentsProps>(({ articleId, topic = "评论", autoLoad, placeTop }, ref) => {
    const [content, setContent] = useState("");
    const commentsBodyRef = useRef<HTMLDivElement>(null);
    const commentUserInfo = useAppSelector(selectCommentUserInfo);
    const [isEditUserInfoVisible, setIsEditUserInfoVisible] = useState(false);

    // 没有评论用户信息，先提示用户录入信息
    const remindCreateUserInfo = useCallback(() => {
        message.warning(`请在${topic}前填写部分必要信息，我们不会公开您的私密信息！`);
        setIsEditUserInfoVisible(true);
    }, [topic]);

    const handlePublish = async () => {
        // 首先校验有没有用户信息
        if (!commentUserInfo) {
            remindCreateUserInfo();
            return Promise.reject();
        }
        if (!content) {
            message.warning("您还未输入任何内容！");
            return Promise.reject();
        }
        const purifiedContent = DOMPurify.sanitize(content);
        if (!purifiedContent) {
            message.warning("您的输入内容无效，请重新输入合法内容！");
            return Promise.reject();
        }
        const params = {
            article_id: articleId,
            content: purifiedContent,
            // 回访url
            jump_url: window.location.href,
            ...commentUserInfo,
        };
        await commentService.add(params);
        // 重置输入内容，防止重复提交
        setContent("");
        message.success(`您的${topic}已经提交成功，待审核后即可生效！`);
    };

    const { trigger: onClickPublish, loading: isPublishLoading } = useAsyncLoading(handlePublish, [
        commentUserInfo,
        remindCreateUserInfo,
        content,
        articleId,
        topic,
    ]);

    useScrollBottom({
        ref: commentsBodyRef,
        onBottomReached: () => {
            console.log("到底了");
        },
        disabled: !autoLoad,
    });

    const [comments, setComments] = useState<CommentDTO[]>([]);

    const [activeId, setActiveId] = useState<number | null>(null);

    const [pageInfo, setPageInfo] = useState({
        pageNo: 1,
        pageSize: 6,
    });

    const prevPageNo = useRef(pageInfo.pageNo);

    const [total, setTotal] = useState(0);

    const isAllLoaded = useMemo(() => total > 0 && total === comments.length, [total, comments]);

    const handleGetComments = async (isLoadMore = false) => {
        const res = await commentService.page({
            ...pageInfo,
            id: articleId,
        });

        if (isLoadMore) {
            setComments((prev) => [...prev, ...res.data]);
        } else {
            setComments(res.data);
        }

        setTotal(res.total);
    };

    const { trigger: getComments, loading: isFetchLoading } = useAsyncLoading(handleGetComments, [pageInfo, articleId]);

    useEffect(() => {
        const isLoadMore = pageInfo.pageNo > 1 && pageInfo.pageNo !== prevPageNo.current;
        getComments(isLoadMore);
    }, [getComments, pageInfo]);

    useEffect(() => {
        prevPageNo.current = pageInfo.pageNo;
    }, [pageInfo]);

    const commentInputRef = useRef<InputRef>(null);

    const createComment = () => {
        commentInputRef.current?.focus();
    };

    const loadMore = () => {
        if (!isFetchLoading && comments.length < total) {
            setPageInfo((prev) => ({ ...prev, pageNo: prev.pageNo + 1 }));
        }
    };

    useImperativeHandle(ref, () => ({
        showEditUserInfoForm: () => setIsEditUserInfoVisible(true),
    }));

    return (
        <CommentsWrapper>
            {placeTop && (
                <div className="leave-comment">
                    <Input
                        ref={commentInputRef}
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        placeholder={`发表${topic}`}
                    />
                    <Button type="primary" size="small" loading={isPublishLoading} onClick={onClickPublish} style={{ marginLeft: "10px" }}>
                        发布
                    </Button>
                </div>
            )}

            <div className="comments__body" ref={commentsBodyRef}>
                {comments.length > 0 && (
                    <ul className="comments__list">
                        {comments.map((comment) => (
                            <li key={comment.id}>
                                <CardComment
                                    comment={comment}
                                    isActive={activeId === comment.id}
                                    onUserInfoEmpty={remindCreateUserInfo}
                                    onSetActive={(id) => setActiveId(id)}
                                />
                            </li>
                        ))}
                    </ul>
                )}
                {comments.length === 0 && !isFetchLoading && (
                    <Empty
                        description={
                            <>
                                暂无{topic}，快来说两句吧！
                                <ButtonCreate type="primary" onClick={createComment}>
                                    创建{topic}
                                </ButtonCreate>
                            </>
                        }
                    />
                )}

                <Skeleton active avatar paragraph={{ rows: 6 }} loading={isFetchLoading} style={{ marginTop: "20px" }} />

                {isAllLoaded && <BottomTips content="没有更多了" />}

                {!isAllLoaded && comments.length > 0 && (
                    <BottomTips
                        children={
                            <Button type="primary" shape="round" onClick={loadMore}>
                                加载更多
                            </Button>
                        }
                    />
                )}
            </div>

            {!placeTop && (
                <div className="leave-comment">
                    <Input
                        ref={commentInputRef}
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        placeholder={`发表${topic}`}
                    />
                    <Button type="primary" size="small" loading={isPublishLoading} onClick={onClickPublish} style={{ marginLeft: "10px" }}>
                        发布
                    </Button>
                </div>
            )}

            <Modal
                title="修改个人信息"
                open={isEditUserInfoVisible}
                footer={null}
                styles={{ body: { paddingTop: "20px" } }}
                onCancel={() => setIsEditUserInfoVisible(false)}
            >
                <CommentUserInfoForm
                    topic={topic}
                    onCancel={() => setIsEditUserInfoVisible(false)}
                    onSuccess={() => setIsEditUserInfoVisible(false)}
                />
            </Modal>
        </CommentsWrapper>
    );
});

export default Comments;

// app/frontend/src/views/article/comments.vue
<!--
 * @author: Tusi
 * @description: 评论区
-->

<template>
    <section class="comments__wrapper">
        <div class="leave-comment" v-if="placeTop">
            <a-input ref="commentInputRef" v-model:value="content" :placeholder="`发表${topic}`" />
            <a-button class="btn-publish" type="primary" size="small" :loading="isPublishLoading" @click="onClickPublish">发布</a-button>
        </div>

        <div v-infinite-scroll="loadMore" :infinite-scroll-distance="50" :infinite-scroll-disabled="!autoLoad" class="comments__body">
            <ul class="comments__list" v-if="comments.length > 0">
                <li v-for="comment in comments" :key="comment.id">
                    <card-comment
                        :comment="comment"
                        :is-active="activeId === comment.id"
                        @userInfoEmpty="onUserInfoEmpty"
                        @setActive="onSetActive"
                    />
                </li>
            </ul>

            <a-empty v-else-if="!isFetchLoading">
                <template #description>
                    暂无{{ topic }}，快来说两句吧！
                    <my-button class="btn-add" type="primary" @click="createComment">创建{{ topic }}</my-button>
                </template>
            </a-empty>

            <a-skeleton :loading="isFetchLoading" active avatar :paragraph="{ rows: 6 }"> </a-skeleton>

            <bottom-tips v-if="isAllLoaded" content="没有更多了" />

            <bottom-tips v-else-if="comments.length > 0">
                <a-button shape="round" type="primary" @click="loadMore">加载更多</a-button>
            </bottom-tips>
        </div>

        <div class="leave-comment" v-if="!placeTop">
            <a-input ref="commentInputRef" v-model:value="content" :placeholder="`发表${topic}`" />
            <a-button class="btn-publish" type="primary" size="small" :loading="isPublishLoading" @click="onClickPublish">发布</a-button>
        </div>

        <a-modal v-model:visible="isEditUserInfoVisible" :footer="null">
            <comment-user-info :topic="topic" @cancel="isEditUserInfoVisible = false" @success="isEditUserInfoVisible = false" />
        </a-modal>
    </section>
</template>

<script lang="ts">
import { ElInfiniteScroll } from "element-plus";
import { computed, defineComponent, reactive, ref } from "vue";
import { useStore } from "vuex";
import { Input, message, Modal } from "ant-design-vue";
import DOMPurify from "dompurify";
import { commentService } from "@/services/comment";
import { CommentDTO } from "@/bean/dto";
import CardComment from "@/components/card/card-comment.vue";
import { useAsyncLoading } from "@/hooks/async";
import { key } from "@/store";
import { app } from "@/main";
import CommentUserInfo from "./comment-user-info.vue";

app.use(ElInfiniteScroll);

export default defineComponent({
    name: "Comments",
    components: {
        CardComment,
        CommentUserInfo,
        [Input.name]: Input,
        [Modal.name]: Modal,
    },
    props: {
        articleId: {
            type: Number,
        },
        topic: {
            type: String,
            default: "评论",
        },
        autoLoad: {
            type: Boolean,
            default: true,
        },
        placeTop: {
            type: Boolean,
            default: false,
        },
    },
    setup(props) {
        // vuex
        const store = useStore(key);

        const comments = ref<CommentDTO[]>([]);

        const activeId = ref(-1);
        const onSetActive = (id: number) => {
            activeId.value = id;
        };

        const total = ref(0);

        const isAllLoaded = computed(() => total.value > 0 && total.value === comments.value.length);

        const pageInfo = reactive({
            pageNo: 1,
            pageSize: 6,
        });

        const handleGetComments = async (isLoadMore = false) => {
            const res = await commentService.page({
                ...pageInfo,
                id: props.articleId,
            });

            if (isLoadMore) {
                comments.value = [...comments.value, ...res.data];
            } else {
                comments.value = res.data;
            }
            total.value = res.total;
        };

        const { trigger: getComments, loading: isFetchLoading } = useAsyncLoading(handleGetComments);

        getComments();

        // 加载更多
        const loadMore = () => {
            if (!isFetchLoading.value && comments.value.length < total.value) {
                pageInfo.pageNo++;
                getComments(true);
            }
        };

        // 评论用户信息
        const commentUserInfo = computed(() => store.state.commentUserInfo);
        const isEditUserInfoVisible = ref(false);

        // 没有评论用户信息，先提示用户录入信息
        const remindCreateUserInfo = () => {
            message.warning(`请在${props.topic}前填写部分必要信息，我们不会公开您的私密信息！`);
            isEditUserInfoVisible.value = true;
        };

        const onUserInfoEmpty = () => {
            remindCreateUserInfo();
        };

        // 评论
        const content = ref("");
        const commentInputRef = ref();
        const createComment = () => {
            commentInputRef.value.focus();
        };
        const handlePublish = async () => {
            // 首先校验有没有用户信息
            if (!commentUserInfo.value) {
                remindCreateUserInfo();
                return;
            }
            if (!content.value) {
                // 必填校验
                message.warning("您还未输入任何内容！");
                return;
            }
            const purifiedContent = DOMPurify.sanitize(content.value);
            if (!purifiedContent) {
                // 输入了非法的内容
                message.warning("您的输入内容无效，请重新输入合法内容！");
                return;
            }

            // 提交评论
            const params = {
                article_id: props.articleId,
                // 用article_id来区分是留言板还是文章评论，留言是没有文章id的，而文章评论是有的
                content: purifiedContent,
                // 默认是未审核状态
                approved: 0,
                // 回访url
                jump_url: window.location.href,
                // 用户信息
                ...store.state.commentUserInfo,
            };

            await commentService.add(params);
            // 重置输入内容，防止重复提交
            content.value = "";
            message.success(`您的${props.topic}已经提交成功，待审核后即可生效！`);
        };

        const { trigger: onClickPublish, loading: isPublishLoading } = useAsyncLoading(handlePublish);

        return {
            comments,
            isFetchLoading,
            createComment,
            loadMore,
            isAllLoaded,
            content,
            onClickPublish,
            isPublishLoading,
            isEditUserInfoVisible,
            commentInputRef,
            onUserInfoEmpty,
            activeId,
            onSetActive,
        };
    },
});
</script>

<style lang="scss" scoped>
.comments__wrapper {
    display: flex;
    flex-direction: column;
    flex: 1;
}

.comments__body {
    overflow: auto;
    flex: 1;
    padding: 20px;
}

.comments__list {
    > li + li {
        margin-top: 20px;
    }
}

:deep(.btn-add) {
    margin: 20px auto;
    display: block;
}

.leave-comment {
    display: flex;
    align-items: center;
    padding: 12px 20px;
    box-shadow: 0 -1px 10px 0 rgba(0, 0, 0, 0.1);
    z-index: 2;
}

:deep(.btn-publish) {
    margin-left: 10px;
}
</style>
