// app/nuxt3-web/app.vue
<template>
    <NuxtLoadingIndicator />
    <a-config-provider
        :locale="zhCN"
        :theme="{
            token: {
                colorPrimary: '#008dff',
                colorLink: '#87b4e2',
            },
        }"
    >
        <NuxtLayout>
            <NuxtPage />
        </NuxtLayout>
    </a-config-provider>
</template>

<script lang="ts" setup>
import zhCN from "ant-design-vue/es/locale/zh_CN";
</script>

<style lang="less" scoped>
.hidden-x {
    overflow-x: hidden;
}

.is-admin {
    height: 100%;
}
</style>

// app/vite-react19/src/App.tsx
import { RouterProvider } from 'react-router-dom'
import { ConfigProvider, Skeleton } from 'antd'
import { Suspense } from 'react'
import zhCN from 'antd/locale/zh_CN'
import { router } from './router'
import 'dayjs/locale/zh-cn'

function App() {
  return (
    <ConfigProvider
      locale={zhCN}
      theme={{
        token: {
          colorPrimary: '#008dff',
          colorLink: '#87b4e2',
          colorLinkHover: '#6d9ccd',
        },
      }}
    >
      <Suspense fallback={<Skeleton />}>
        <RouterProvider router={router} />
      </Suspense>
    </ConfigProvider>
  )
}

export default App
